services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - HVAC_CONNECTION_STRING=192.168.1.108:12416
      - LISTEN_PORT=9090
      - ALLOW_ORIGIN=*
