FROM freepascal/fpc:3.2.2-buster-full AS build
WORKDIR /build
RUN mkdir src
COPY src/HvacUnits ./src/HvacUnits
COPY src/HvacApi ./src/HvacApi
WORKDIR /build/src/HvacApi
RUN ./build.sh release

FROM alpine:3.20 AS runtime
RUN apk add --no-cache libc6-compat
RUN adduser -D web
USER web
WORKDIR /app
COPY --from=build /build/src/HvacApi/out/HvacApiApp .
EXPOSE 9090
ENTRYPOINT ["/app/HvacApiApp"]
