services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.Hvac.Api
    ports:
      - "9090:9090"
    environment:
      - HVAC_CONNECTION_STRING=simulator:12416
      - LISTEN_PORT=9090
      - API_KEY=abcdef
      - ALLOW_ORIGIN=*

  web:
    build:
      context: .
      dockerfile: Dockerfile.Hvac.Web
    ports:
      - "8080:8080"

  simulator:
    build:
      context: .
      dockerfile: Dockerfile.Hvac.Simulator
    ports:
      - "12416:12416"
    environment:
      - LISTEN_IFACE=0.0.0.0
      - LISTEN_PORT=12416
